[tool.poetry]
name = "neutral-density"
version = "0.1.0"
description = ""
authors = ["Romain <romain.caneill@zaclys.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jax = {extras = ["cuda12"], version = "^0.5.2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
